# Generated by Django 2.2.5 on 2020-07-08 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mstore', '0006_auto_20200707_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
    ]
