# Generated by Django 2.2.5 on 2020-07-09 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mstore', '0009_remove_cart_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='CIM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='OIM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mstore.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_now_add=True)),
                ('shipment_date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='cart',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='item',
        ),
        migrations.DeleteModel(
            name='Order_detail',
        ),
        migrations.AddField(
            model_name='oim',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mstore.Order'),
        ),
        migrations.AddField(
            model_name='cim',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mstore.Cart'),
        ),
        migrations.AddField(
            model_name='cim',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mstore.Item'),
        ),
    ]
