# Generated by Django 2.2.5 on 2020-07-12 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mstore', '0012_auto_20200709_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mstore.Product'),
        ),
        migrations.AlterField(
            model_name='oim',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mstore.Item'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('rating', models.IntegerField(max_length=5)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mstore.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
