# Generated by Django 2.2.5 on 2020-07-12 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mstore', '0013_auto_20200712_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='new_arrival',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mstore.Product'),
        ),
        migrations.AlterField(
            model_name='oim',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mstore.Item'),
        ),
    ]
